config:
  target: "http://localhost:8080"
  phases:
    - duration: 60
      arrivalRate: 1
scenarios:
  - name: Get Product
    flow:
      - get:
          name: "products"
          url: "/products/1000000"